export const GAME = {
  WIDTH: 700,
  HEIGHT: 400,
  MAX_ENERGY: 100,
  HURT_DAMAGE: 30,
  HURT_INVINCIBLE_MS: 1200,
  ENEMY_CHASE_SPEED: 110,
  PLAYER_BASE_SPEED: 220,
  WORLD_BOUNDS_TOP: 50,
  GRID_SIZE_X: 40,
  GRID_SIZE_Y: 40,
} as const;

export const POWERUP = {
  SPEED_DURATION: 6000,
  SHIELD_DURATION: 5000,
  MAGNET_DURATION: 8000,
  PHASE_DURATION: 7000,
  SPAWN_INTERVAL_BASE: 12000,
  SPAWN_INTERVAL_MIN: 5000,
  SPAWN_INTERVAL_DECREMENT: 300,
  EXPIRE_TIME: 7000,
  WELCOME_DELAY_L1: 5000,
  WELCOME_DELAY_DEFAULT: 8000,
  SPEED_MULTIPLIER: 1.6,
  MAGNET_RANGE: 180,
  MAGNET_PULL: 350,
  TRAIL_SPAWN_CHANCE: 0.25,
} as const;

export const COIN = {
  GOLD: { VALUE: 10, ENERGY: 20 },
  SILVER: { VALUE: 25, ENERGY: 25 },
  RAINBOW: { VALUE: 50, ENERGY: 35 },
  SPAWN_MARGIN: 30,
  SPAWN_OFFSET_Y: 50,
} as const;

export const CRISIS = {
  CRITICAL_THRESHOLD: 25,
  AGONIC_THRESHOLD: 10,
  FLASH_INTERVAL: 2000,
  SHAKE_INTERVAL: 2000,
  HEARTBEAT_CRITICAL_BPM: 60,
  HEARTBEAT_AGONIC_BPM: 120,
} as const;

export const PAUSE = {
  OVERLAY_ALPHA: 0.75,
  FADE_IN_DURATION: 200,
  FADE_OUT_DURATION: 100,
} as const;

export const COMBO = {
  TIME_WINDOW_MS: 2000,
  TIER_3_MULTIPLIER: 1.5,
  TIER_5_MULTIPLIER: 2.0,
} as const;

export const RANKING = {
  MAX_ENTRIES: 10,
  STORAGE_KEY: 'phantom_ranking',
} as const;
